### ISSUE TITLE
Fix Cookie issue

### ISSUE THREAD

**Issue by 0auBSQ** [0auBSQ/MiniBlog#2]
Make POST requests work with session tokens, investigate more about `withCredentials` and `Access-Control-Allow-Credentials`

**Comment by Artheriom** [comment]
Hi, 

I'm wondering why you still use cookies for your authentication token. :stuck_out_tongue:  As you're building an API, the proper way to send authentication details is to use "Authorization" header. When login succeed, the API would return a `201 CREATED`, with an `Authorization` header, set to your token ( `w.Header().Set("Authorization", your_token_variable);`).

Then, you will be able to save it to localStorage in your Vue.JS app

```js
axios.post("my_auth_url", payload)
  .then(response => {
    localStorage.token=response.headers.authorization;
  }
```

And use it for various requests : 
```js
axios.get("my_get_url", {headers: {Authorization: localStorage.token}})
...

axios.post("my_get_url", payload, {headers: {Authorization: localStorage.token}})
...
``` 

Of course, it would be nicer to use a Vue Store instead of accessing directly localStorage, but it will be a good start :smile: 

To read header in Go : `r.Header.Get("Authorization")`


The point is that Cookies are very limited. Even if you're simply using it for token storage, cookies are scoped to a single domain : a cookie generated by `localhost:8080` would not be accessible by `localhost:6969` by example. It leads to tricky hacks to make things works.


If you still have trouble, try to replace your `handlers.AllowedOrigins([]string{"http://localhost:8080"})` to `handlers.AllowedOrigins([]string{"*"})`. 

Have fun ! :relaxed: 


PS : curl request would be like this : `curl -i -H "Authorization: your_token" http://hostname/resource`

**Comment by 0auBSQ** [comment]
Hello,

Thank you a lot once again for your help !
I was pretty busy recenty finishing another project (https://github.com/0auBSQ/In_The_Shadows), but I will try the changes asap !
About cookies, I usually use them to be able to combine them with the Http Only (and Secure) flags, but the localStorage method seems safe as well.
I wanted to avoid using JWT because of some exploits (especially null algorithm and RSA pubkey vulnerability, implying that more back-end validation might be necessary) and the lack of relevant advantages about using them.

We actually use a store, so if it's safe enough to put it within the store it would be great 😄 

About cookies it's pretty weird, I didn't had any issues to send cross-domain cookies from a React Front to a Node Back, even if the localStorage method works, I would still be curious about why this strange issue with cookies occurs.

About the `Allowed Origins` header, I would prefer to avoid the wildcard use (mainly for security concerns), but since we currently don't get CORS'ed by precising explicitely the origin it should work well, I'll try anyway if I still have trouble then ^^

Thanks ! 😃

**Comment by 0auBSQ** [comment]
It worked ! Thank you again :) 

There were few things to setup as well : 
- On the Gorilla handlers :
```
handlers.ExposedHeaders([]string{"*"})
```
(A CORS request needs the `Access-Control-Expose-Headers` options to be set)
- On the Vuex store, npm install and import this : 
```
import createPersistedState from 'vuex-persistedstate'
```
And set this : 
```
export default new Vuex.Store({
    plugins: [createPersistedState({
        storage: window.sessionStorage,
    })],
    state: {
        ....
    },
    ....
});
```
To keep the store state persistent troughout the session.

We're still have few things to fix, but there shouldn't have any problem after this :)
I'll close this issue as fixed, but I'll let the 1st one open if you have any further suggestions !
